// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Przychodnia.Server.Models;

#nullable disable

namespace Przychodnia.Server.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Przychodnia.Shared.Rang", b =>
                {
                    b.Property<int>("RangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangID"), 1L, 1);

                    b.Property<string>("RangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RangID");

                    b.ToTable("Rangs");

                    b.HasData(
                        new
                        {
                            RangID = 1,
                            RangName = "Admin"
                        },
                        new
                        {
                            RangID = 2,
                            RangName = "Doktor"
                        },
                        new
                        {
                            RangID = 3,
                            RangName = "Pacjent"
                        });
                });

            modelBuilder.Entity("Przychodnia.Shared.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RangID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RangID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 995213523765L,
                            Email = "m.kowal@gmail.com",
                            Name = "Marcel",
                            Password = "MarcelKowal1",
                            PhotoPath = "Images/Marcel.png",
                            RangID = 1,
                            Surname = "Kowal"
                        },
                        new
                        {
                            ID = 99768496534L,
                            Email = "w.tak@gmail.com",
                            Name = "Wiktoria",
                            Password = "Wika123",
                            PhotoPath = "Images/Wiktoria.png",
                            RangID = 2,
                            Surname = "Tak"
                        },
                        new
                        {
                            ID = 99574836547L,
                            Email = "c.muza@gmail.com",
                            Name = "Cezary",
                            Password = "Czarus14",
                            PhotoPath = "Images/Cezary.png",
                            RangID = 3,
                            Surname = "Muza"
                        });
                });

            modelBuilder.Entity("Przychodnia.Shared.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Successful")
                        .HasColumnType("bit");

                    b.HasKey("VisitId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            Date = new DateTime(2022, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Badanie Rozwojowe",
                            DoctorName = "Cezary Ochlik",
                            Duration = 3,
                            Name = "Badanie",
                            Paid = true,
                            PatientName = "Franek Kilimandżaro",
                            Successful = true
                        },
                        new
                        {
                            VisitId = 2,
                            Date = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Badanie Rozwojowe1",
                            DoctorName = "Wiktoria Stępa",
                            Duration = 4,
                            Name = "Badanie1",
                            Paid = true,
                            PatientName = "Kamil Sufranek",
                            Successful = false
                        });
                });

            modelBuilder.Entity("Przychodnia.Shared.User", b =>
                {
                    b.HasOne("Przychodnia.Shared.Rang", "RangName")
                        .WithMany()
                        .HasForeignKey("RangID");

                    b.Navigation("RangName");
                });
#pragma warning restore 612, 618
        }
    }
}
